name: Deploy Documentation

on:
  push:
    branches:
      - master
    paths:
      - "docs/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Call deploy hook
        run: curl -X POST ${{ secrets.DEPLOY_HOOK }}
